export const PROPERTIES = 'PROPERTIES';
export const PROPERTY = 'PROPERTY';

export const AUTH = 'AUTH';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const CREATE_INVESTMENT = 'CREATE_INVESTMENT';
export const GET_INVESTMENT = 'GET_INVESTMENT';
export const GET_SINGLE_INVESTMENT = 'GET_SINGLE_INVESTMENT';
export const INCREMENT_INVESTMENT = 'INCREMENT_INVESTMENT';
export const RETRIEVE_PAYMENT = 'RETRIEVE_PAYMENT';

export const WITHDRAW_FUNDS = 'WITHDRAW_FUNDS';
export const GET_WITHDRAWALS = 'GET_WITHDRAWALS';
export const GET_WITHDRAWAL = 'GET_WITHDRAWAL';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const STATIC_INVESTMENTS = 'STATIC_INVESTMENTS';

export const VERIFY_USER = 'VERIFY_USER';
export const GET_IDENTITIES = 'GET_IDENTITIES';
export const GET_IDENTITY = 'GET_IDENTITY';
